#!/bin/bash
# AURASPHERE CRM - QUICK START GUIDE

echo "🚀 AuraSphere CRM - Quick Start"
echo "================================"
echo ""
echo "📁 Project Location:"
echo "   C:\Users\PC\AuraSphere\crm\aura_crm"
echo ""
echo "🔧 Development Commands:"
echo ""
echo "1. Run locally (Chrome):"
echo "   flutter run -d chrome"
echo ""
echo "2. Build for production:"
echo "   flutter clean"
echo "   flutter pub get"
echo "   flutter build web --release"
echo ""
echo "3. Check code quality:"
echo "   flutter analyze"
echo ""
echo "4. Hot reload while running:"
echo "   Press 'r' in the terminal"
echo ""
echo "🌐 Key URLs:"
echo "   App: http://localhost:PORT (shown when running)"
echo "   Supabase: https://uielvgnzaurhopolerok.supabase.co"
echo ""
echo "📋 Key Files:"
echo "   - lib/main.dart              (Entry point with auth)"
echo "   - lib/landing_page.dart      (Public landing page)"
echo "   - lib/sign_in_page.dart      (Authentication)"
echo "   - lib/dashboard_page.dart    (Protected area)"
echo "   - lib/theme/modern_theme.dart (Design system)"
echo ""
echo "🔐 Important:"
echo "   - Supabase credentials configured in lib/main.dart"
echo "   - Auth system uses Supabase auth"
echo "   - All pages check user authentication"
echo ""
echo "✅ Status: PRODUCTION READY"
echo "================================"
